pipeline {
    agent any

    parameters {
       string(name: 'Branch', defaultValue: 'master', description: 'Git branch to run tests')
       string(name: 'Tags', defaultValue:'@ui', description: 'Tags to run test for')
    }
    stages {
        stage('Clean Up') {
            steps {
                cleanWs()
            }
        }
        stage('Build') {
            steps {
                 sh './gradlew build'
            }
        }
        stage('Start Test Execution') {
            steps {
                sh './gradlew cucumber -Dtags=${params.Tags}'
            }
        }
    }
}