pipeline {
    agent any

    parameters {
       string(name: 'Branch', defaultValue: 'master', description: 'Git branch to run tests')
       string(name: 'Tags', defaultValue:'@ui', description: 'Tags to run test for')
    }
    stages {

        stage('Build') {
            steps {
                 bat './gradlew build'
            }
        }
        stage('Start Test Execution') {
            steps {
                bat './gradlew cucumber -Dtags="${params.Tags}"'
            }
        }
    }
}